import type { Metadata } from "next";
import "../assets/sass/globals.scss";
import MainNavigation from "@/components/nav/main-navigation";

export const metadata: Metadata = {
  title: "Ding Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainNavigation />
        {children}
        <div id="notifications" />
      </body>
    </html>
  );
}
